##############################
# Filebeat example config
# Path: docs/user_guides/agents/filebeat.example.yml
# Purpose: Collect Linux logs and forward to Logstash (recommended)
##############################
# Filebeat inputs
filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /var/log/messages
      - /var/log/syslog
      - /var/log/auth.log
      - /var/log/*.log
    fields:
      env: production
    fields_under_root: true

# Add metadata about the host/device. Beats will also add host.* fields automatically.
processors:
  - add_host_metadata: ~
  - add_cloud_metadata: ~
  - add_fields:
      target: ''
      fields:
        product: cybergard
        device_role: server

# Send to Logstash for parsing & transformation
output.logstash:
  # Logstash hosts (replace with your collector)
  hosts: ["logstash.example.com:5044"]
  # Enable SSL if Logstash is behind TLS
  ssl:
    enabled: true
    certificate_authorities: ["/etc/pki/tls/certs/ca.crt"]

# Optional: keep local file-based queue for resilience
queue.spool:
  file: /var/lib/filebeat/queue

logging.level: info
logging.to_files: true
logging.files:
  path: /var/log/filebeat
  name: filebeat
  keepfiles: 7
  permissions: 0644

# Example additional fields that will be merged into events
fields:
  device_group: linux-servers
